import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const jalnan2ttf = localFont({
  src: "../../fonts/Jalnan2TTF.ttf",
  display: "swap",
  weight: "45 920",
  variable: "--font-jalnan2ttf"
});

const jalnan2 = localFont({
  src: "../../fonts/Jalnan2.otf",
  display: "swap",
  variable: "--font-jalnan2"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jalnan2ttf.variable} ${jalnan2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
